[package]
name = "madinah-mushaf"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["Naif Alsultan"]
license = "MIT"
description = "A Typst package for rendering Quranic text using the Madinah Mushaf (King Fahd Complex) fonts."
homepage = "https://github.com/NaifAlsultan/typst-quran-package"
repository = "https://github.com/NaifAlsultan/typst-quran-package"
keywords = ["quran", "mushaf", "madinah", "text"]
categories = ["text"]
exclude = [
  ".github",
  "docs",
  "scripts",
  "tests",
  ".typstignore",
  "Justfile",
  "fonts",
  "flake.nix",
  "flake.lock",
  "GEMINI.md",
  "reference",
  ".gitignore",
]
